---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop
  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 2.6
          - 2.7
          - 3.0
          - 3.1
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run the test suite
        run: bundle exec rspec
